#pragma once

#include "pch.h"

enum class KeyboardKeys
{
    KEY_Backspace = VK_BACK,
    KEY_Tab = VK_TAB,
    KEY_Enter = VK_RETURN,
    KEY_Shift = VK_SHIFT,
    KEY_Ctrl = VK_CONTROL,
    KEY_Alt = VK_MENU,
    KEY_Pause = VK_PAUSE,
    KEY_CapsLock = VK_CAPITAL,
    KEY_Escape = VK_ESCAPE,
    KEY_Space = VK_SPACE,
    KEY_PageUp = VK_PRIOR,
    KEY_PageDown = VK_NEXT,
    KEY_End = VK_END,
    KEY_Home = VK_HOME,
    KEY_LeftArrow = VK_LEFT,
    KEY_UpArrow = VK_UP,
    KEY_RightArrow = VK_RIGHT,
    KEY_DownArrow = VK_DOWN,
    KEY_Select = VK_SELECT,
    KEY_Print = VK_PRINT,
    KEY_Execute = VK_EXECUTE,
    KEY_PrintScreen = VK_SNAPSHOT,
    KEY_Insert = VK_INSERT,
    KEY_Delete = VK_DELETE,
    KEY_Help = VK_HELP,
    KEY_Zero = 0x30,  // '0'
    KEY_One = 0x31,   // '1'
    KEY_Two = 0x32,   // '2'
    KEY_Three = 0x33, // '3'
    KEY_Four = 0x34,  // '4'
    KEY_Five = 0x35,  // '5'
    KEY_Six = 0x36,   // '6'
    KEY_Seven = 0x37, // '7'
    KEY_Eight = 0x38, // '8'
    KEY_Nine = 0x39,  // '9'
    KEY_A = 0x41,     // 'A'
    KEY_B = 0x42,     // 'B'
    KEY_C = 0x43,     // 'C'
    KEY_D = 0x44,     // 'D'
    KEY_E = 0x45,     // 'E'
    KEY_F = 0x46,     // 'F'
    KEY_G = 0x47,     // 'G'
    KEY_H = 0x48,     // 'H'
    KEY_I = 0x49,     // 'I'
    KEY_J = 0x4A,     // 'J'
    KEY_K = 0x4B,     // 'K'
    KEY_L = 0x4C,     // 'L'
    KEY_M = 0x4D,     // 'M'
    KEY_N = 0x4E,     // 'N'
    KEY_O = 0x4F,     // 'O'
    KEY_P = 0x50,     // 'P'
    KEY_Q = 0x51,     // 'Q'
    KEY_R = 0x52,     // 'R'
    KEY_S = 0x53,     // 'S'
    KEY_T = 0x54,     // 'T'
    KEY_U = 0x55,     // 'U'
    KEY_V = 0x56,     // 'V'
    KEY_W = 0x57,     // 'W'
    KEY_X = 0x58,     // 'X'
    KEY_Y = 0x59,     // 'Y'
    KEY_Z = 0x5A,     // 'Z'
    KEY_LeftWindows = VK_LWIN,
    KEY_RightWindows = VK_RWIN,
    KEY_Applications = VK_APPS,
    KEY_Sleep = VK_SLEEP,
    KEY_NumPad0 = VK_NUMPAD0,
    KEY_NumPad1 = VK_NUMPAD1,
    KEY_NumPad2 = VK_NUMPAD2,
    KEY_NumPad3 = VK_NUMPAD3,
    KEY_NumPad4 = VK_NUMPAD4,
    KEY_NumPad5 = VK_NUMPAD5,
    KEY_NumPad6 = VK_NUMPAD6,
    KEY_NumPad7 = VK_NUMPAD7,
    KEY_NumPad8 = VK_NUMPAD8,
    KEY_NumPad9 = VK_NUMPAD9,
    KEY_Multiply = VK_MULTIPLY,
    KEY_Add = VK_ADD,
    KEY_Separator = VK_SEPARATOR,
    KEY_Subtract = VK_SUBTRACT,
    KEY_Decimal = VK_DECIMAL,
    KEY_Divide = VK_DIVIDE,
    KEY_F1 = VK_F1,
    KEY_F2 = VK_F2,
    KEY_F3 = VK_F3,
    KEY_F4 = VK_F4,
    KEY_F5 = VK_F5,
    KEY_F6 = VK_F6,
    KEY_F7 = VK_F7,
    KEY_F8 = VK_F8,
    KEY_F9 = VK_F9,
    KEY_F10 = VK_F10,
    KEY_F11 = VK_F11,
    KEY_F12 = VK_F12,
    KEY_NumLock = VK_NUMLOCK,
    KEY_ScrollLock = VK_SCROLL,
    KEY_LeftShift = VK_LSHIFT,
    KEY_RightShift = VK_RSHIFT,
    KEY_LeftControl = VK_LCONTROL,
    KEY_RightControl = VK_RCONTROL,
    KEY_LeftMenu = VK_LMENU,
    KEY_RightMenu = VK_RMENU,
    KEY_BrowserBack = VK_BROWSER_BACK,
    KEY_BrowserForward = VK_BROWSER_FORWARD,
    KEY_BrowserRefresh = VK_BROWSER_REFRESH,
    KEY_BrowserStop = VK_BROWSER_STOP,
    KEY_BrowserSearch = VK_BROWSER_SEARCH,
    KEY_BrowserFavorites = VK_BROWSER_FAVORITES,
    KEY_BrowserHome = VK_BROWSER_HOME,
    KEY_VolumeMute = VK_VOLUME_MUTE,
    KEY_VolumeDown = VK_VOLUME_DOWN,
    KEY_VolumeUp = VK_VOLUME_UP,
    KEY_MediaNextTrack = VK_MEDIA_NEXT_TRACK,
    KEY_MediaPrevTrack = VK_MEDIA_PREV_TRACK,
    KEY_MediaStop = VK_MEDIA_STOP,
    KEY_MediaPlayPause = VK_MEDIA_PLAY_PAUSE,
    KEY_LaunchMail = VK_LAUNCH_MAIL,
    KEY_LaunchMediaSelect = VK_LAUNCH_MEDIA_SELECT,
    KEY_LaunchApp1 = VK_LAUNCH_APP1,
    KEY_LaunchApp2 = VK_LAUNCH_APP2,
    KEY_OEM1 = VK_OEM_1,
    KEY_Plus = VK_OEM_PLUS,
    KEY_Comma = VK_OEM_COMMA,
    KEY_Minus = VK_OEM_MINUS,
    KEY_Period = VK_OEM_PERIOD,
    KEY_OEM2 = VK_OEM_2,
    KEY_OEM3 = VK_OEM_3,
    KEY_OEM4 = VK_OEM_4,
    KEY_OEM5 = VK_OEM_5,
    KEY_OEM6 = VK_OEM_6,
    KEY_OEM7 = VK_OEM_7,
    KEY_OEM8 = VK_OEM_8,
    KEY_OEM102 = VK_OEM_102
};